---
- name: Ensure optional apt dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    update_cache: yes

- name: Add repo keys
  apt_key:
    url: "{{ item }}"
  loop: "{{ common_core_keys | union(common_extra_keys) | union(common_custom_keys) }}"

- name: Add repos
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ common_core_repos | union(common_extra_repos) | union(common_custom_repos) }}"

- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install packages
  apt:
    name: "{{ common_core_packages | union(common_extra_packages) | union(common_custom_packages) }}"
