---
- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install packages
  apt:
    name: "{{ common_core_packages | union(common_extra_packages) | union(common_custom_packages) }}"
