---
- name: Write the apt sources file
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install core/basic packages
  apt:
    name: "{{ common_core_packages }}"

- name: Install extra packages
  apt:
    name: "{{ common_extra_packages }}"

- name: Install custom packages
  apt:
    name: "{{ common_custom_packages}}"
  when: common_custom_packages is defined
