---
- name: Write the apt sources file
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root

- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install common packages
  apt:
    name:
      - vim-nox
      - git
      - ctags
      - sudo
      - zsh
      - nano
      - openssh-server
      - htop
      - kbd
      - man
      - iproute2
      - iputils-ping
      - less
      - psmisc
