---
- name: Update repositories cache and accept new releaseinfo
  shell: apt-get update --allow-releaseinfo-change
  
- name: Install core packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - console-setup
      - kbd
      - locales

- name: Add repo keys
  apt_key:
    url: "{{ item }}"
  loop: "{{ common_extra_keys }}"

- name: Add repos
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ common_extra_repos }}"

- name: Install extra packages
  apt:
    name: "{{ common_extra_packages }}"
