---
- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Install common packages @Debian
  apt:
    name:
      - vim-nox
      - git
      - ctags
      - sudo
      - zsh
      - aptitude
      - needrestart
  when: ansible_os_family == "Debian"

- name: Install common packages @Gentoo
  portage:
    sync: yes
    package: "{{ item }}"
    state: present
    update: true
  with_items:
    - "app-editors/vim"
    - "app-admin/sudo"
    - "dev-util/ctags"
    - "dev-vcs/git"
    - "app-shells/zsh"
  when: ansible_os_family == "Gentoo"

