- name: Set keyboard layout
  lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBLAYOUT="
    line: "XKBLAYOUT={{ keyboard_layout | default('us,de') }}"

- name: Install locales
  locale_gen:
    name: "{{ item }}"
  with_items: "{{ locales | default('en_US.UTF-8') }}"

- name: Set default language
  lineinfile:
    path: /etc/default/locale
    regex: "^LANG="
    line: "LANG={{ default_language | default('') }}"
