---
- name: Set keyboard layout
  lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBLAYOUT="
    line: "XKBLAYOUT={{ common_keyboard_layout }}"

- name: Install locales
  community.general.locale_gen:
    name: "{{ item }}"
  with_items: "{{ common_locales }}"

- name: Set default language
  lineinfile:
    path: /etc/default/locale
    regexp: ^LANG=
    line: 'LANG="{{ common_default_language }}"'
    create: True
