---
- import_tasks: common_packages.yml
  tags:
    - packages
- import_tasks: users.yml
  tags:
    - user
- import_tasks: hostname.yml
  tags:
    - hostname
- import_tasks: locale.yml
  tags:
    - localization
