---
- import_tasks: common_packages.yml
  tags:
    - packages
  when: "{{ not common_skip_packages }}"

- import_tasks: locale.yml

- import_tasks: users.yml
  tags:
    - user

- import_tasks: hostname.yml

- import_tasks: extra_files.yml
