---
- name: Ensure the Host part of the SSH client config is commented in
  lineinfile:
    name: /etc/ssh/ssh_config
    regexp: "^\\s*#\\s*Host\\s*\\*"
    line: "Host *"
    backrefs: yes

- name: Disable weak SSH client key exchange algorithms
  lineinfile:
    name: /etc/ssh/ssh_config
    regexp: "^\\s*#?\\s*KexAlgorithms"
    line: "    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
    insertafter: "^\\s*Host \\*"

- name: Disable weak SSH client key algorithms for authentication
  lineinfile:
    name: /etc/ssh/ssh_config
    regexp: "^\\s*#\\s*IdentityFile ~/.ssh/id_{{ item }}$"
    state: absent
    insertafter: "^\\s*Host \\*"
  with_items:
    - dsa
    - ecdsa

- name: Enable SSH public key authentication in client
  lineinfile:
    name: /etc/ssh/ssh_config
    regexp: "^\\s*#?\\s*PubkeyAuthentication"
    line: "    PubkeyAuthentication yes"
    insertafter: "^\\s*Host \\*"

- name: Disable weak server keys in SSH client
  lineinfile:
    name: /etc/ssh/ssh_config
    regexp: "^\\s*#?\\s*HostKeyAlgorithms"
    line: "    HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa"
    insertafter: "^\\s*Host \\*"

- name: Disable weak SSH client ciphers
  lineinfile:
    name: /etc/ssh/ssh_config
    regexp: "^\\s*#?\\s*Ciphers"
    line: "    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    insertafter: "^\\s*Host \\*"

- name: Disable weak SSH client MACs
  lineinfile:
    name: /etc/ssh/ssh_config
    regexp: "^\\s*#?\\s*MACs"
    line: "    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com"
    insertafter: "^\\s*Host \\*"
