---
- name: Make sure admin group(wheel) is present
  group:
    name: wheel
    state: present
    system: yes

- name: Create admin users
  user:
    comment: "{{ item.value.name }}"
    createhome: yes
    groups: dialout,users,wheel
    state: present
    system: no
    name: "{{ item.key }}"
    shell: "{{ item.value.shell|default('/bin/bash') }}"
    password: "{{ item.value.passwd|default('$6$mDFWEb5pDY$C9ZTuNjTTSyh0uIBoZALAV6isFY4dO8gBN2/xJ0yX2rejvr2wKp/wMmHwvoC.gD8NaeozxjhWvNHp3rJEJdJj1') }}"
  with_dict: "{{ admins }}"

- name: Update ssh keys for users
  authorized_key:
    exclusive: yes
    key: "{% for key in admins[item]['keys'] %}{{ key }}\n{% endfor %}"
    state: present
    user: "{{ item }}"
    validate_certs: yes
  with_items: "{{ admins }}"

- name: Update ssh keys for root
  authorized_key:
    exclusive: yes
    key: "{% for user in admins %}{% for key in admins[user]['keys'] %}{{ key }}\n{% endfor %}{% endfor %}"
    state: present
    user: "root"
    validate_certs: yes

- name: Grant all admin users root privilages
  lineinfile:
    create: yes
    dest: /etc/sudoers
    regexp: '^%wheel\s'
    insertafter: 'Same thing without a password'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    mode: 0400
    owner: root
    group: root
    state: present
